### ISSUE TITLE
idea for the program

### ISSUE THREAD

**Issue by Fl4keyJakey** [bruxo00/steam-auto-shutdown#2]
i have an idea where if the download is under 0.09 mb/s it wont reset the idle detector,
because everytime i try some windows program uses like 0.03 mb/s and that resets it.

**Comment by Fl4keyJakey** [comment]
note: windows won't allow me to close it

**Comment by diogomartino** [comment]
Hello! The idle detector already has that kind of threshold to stop resetting the idle counter, but it is probably is way to low (0.001 mb/s I think?). Also, the closing problem has something to do with the Metro Framework. I will try to fix both issues in the future, right know I don't have too much time to do it. 

One workaround to the app not closing is closing with the Exit button. This way it will close the app for sure. The problem happens when you close via de X default button on the top or right clicking on the task bar and hitting close window.

Anyway, thanks for your suggestions!
